site_name: Mapping Mozzie
site_author: Paul Schickler
## copyright: copyright Paul Schickler 2021
nav:
    - Home: index.md
    - Parts: partslist.md
    - Tasks: taskorder.md
    - Tools & Supplies: toolsetc.md
    - Safety: safety.md

## theme: readthedocs
theme:
    name: mkdocs
    ## name: readthedocs
    navigation_depth: 2
    nav_style: dark
    ## include_sidebar: false ## <- does this do anything?
    ## show_sidebar: false <- not a thing
